# Generated by Django 2.2.17 on 2020-12-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutorialDjango', '0002_auto_20201209_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
    ]
